### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by momomingchen** [ggerganov/imgui-em#1]
Hi ggerganov,
I am new to C++ programming. I tried to compile the imgui port by running compile.sh in a Window command prompt but failed. Is compile.sh only run in Linux environment?
Sorry about the ignorant question!
momomingchen

**Comment by ggerganov** [comment]
Hello,

Yes, "compile.sh" is supposed to be run in Linux environment. Try the "compile_win.bat" script instead (just added). Also make sure you have installed the Emscripten compiler (http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html).

**Comment by momomingchen** [comment]
Thank for your prompt response!
I have just followed your Build instruction and run compile_win.bat instead of ./configure.sh. Here is the error I have.

C:\Users\hoiching\Documents\eclipse-workspace\imgui-em>compile_win
WARNING:root:retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_9.zip
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\emcc", line 1128, in <module>
    args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
  File "C:\Program Files\Emscripten\emscripten\1.35.0\emcc", line 1108, in get_bitcode_args
    args = system_libs.process_args(args, shared.Settings)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 527, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\ports\sdl.py", line 57, in process_args
    get(ports, settings, shared)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\ports\sdl.py", line 23, in get
    ports.fetch_project('sdl2', 'https://github.com/emscripten-ports/SDL2/archive/' + TAG + '.zip', 'SDL2-' + TAG)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 469, in fetch_project
    retrieve()
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 441, in retrieve
    f = urllib2.urlopen(url)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>

**Comment by momomingchen** [comment]
Hi again,

After several hours of goggling, finally managed to build the codes. End up it is the Python SSL problem. I need to use Python 2.7.14. instead of 2.7.5.3 bundled with Emscripten. The latest Emscripten is required to cope with the new Python syntax. Also, I need to manually change the configure file "~./emscripten" to point to the Python 2.7.14.  ./emsdk activate latest always reset to use python 2.7.5.3.

Though the compile is successful and I can use browser to open the desired html page, there are quite a lot of warnings during the compilation process. I wonder if it would cause some hidden problem.

Anyway, thank you for your advice!

Tom

**Comment by ggerganov** [comment]
Glad you've fixed it! If you encounter any problems, please share them.
